export const operatorMappings: Record<string, Record<string, string>> = {
  text: {
    equals: "equals",
    contains: "contains",
    starts_with: "starts_with",
    ends_with: "ends_with",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  email: {
    equals: "equals",
    contains: "contains",
    starts_with: "starts_with",
    ends_with: "ends_with",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  phone: {
    equals: "equals",
    contains: "contains",
    starts_with: "starts_with",
    ends_with: "ends_with",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  picklist: {
    is: "in",
    is_not: "not_in",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  ownerlookup: {
    is: "equals",
    is_not: "not_equal",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  lookup: {
    is: "equals",
    is_not: "not_equal",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  datetime: {
    between: "between",
    before: "before",
    after: "after",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  date: {
    between: "between",
    before: "before",
    after: "after",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  double: {
    equals: "equals",
    not_equal: "not_equal",
    lt: "less_than",
    lte: "less_equal",
    gt: "greater_than",
    gte: "greater_equal",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  integer: {
    equals: "equals",
    not_equal: "not_equal",
    lt: "less_than",
    lte: "less_equal",
    gt: "greater_than",
    gte: "greater_equal",
    is_empty: "is_empty",
    is_not_empty: "is_not_empty",
  },
  boolean: {
    is: "equals",
  },
};
